// File: ram.v
// Generated by MyHDL 0.9.0
// Date: Sun May  6 16:03:39 2018


`timescale 1ns/10ps

module ram (
    clk,
    data_a,
    data_b,
    addr_a,
    addr_b,
    we_a,
    we_b,
    q_a,
    q_b
);


input clk;
input [7:0] data_a;
input [7:0] data_b;
input [9:0] addr_a;
input [9:0] addr_b;
input we_a;
input we_b;
output [7:0] q_a;
reg [7:0] q_a;
output [7:0] q_b;
reg [7:0] q_b;


reg [7:0] ram [0:1024-1];




always @(posedge clk) begin: RAM_PORT_A
    if (we_a) begin
        ram[addr_a] <= data_a;
        q_a <= data_a;
    end
    else begin
        q_a <= ram[addr_a];
    end
end


always @(posedge clk) begin: RAM_PORT_B
    if (we_b) begin
        ram[addr_b] <= data_b;
        q_b <= data_a;
    end
    else begin
        q_b <= ram[addr_b];
    end
end

endmodule
